### PR TITLE
TEST contribution

### PR DESCRIPTION
**Pull request by anxumalo**
# Contributor guide pull request

Thanks for contributing to the [Microsoft Learn contributor guide](https://learn.microsoft.com/contribute/?branch=main). Please read these instructions for processing your pull request (PR). Once you've read this text, delete it and write a brief description of the changes you're proposing.

## Quality control

- [ ] 1. **Successful build with no warnings**: Review the build status to make sure **all checks are green** (Succeeded).

- [ ] 2. **#Sign-off**: Once the PR is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the PR. Signing off means the document is ready for review and can be published at any time.

## Merge and publish

- All PRs to this repository are manually reviewed and merged.
- Once all feedback on the PR is addressed, we'll merge the PR into the main branch.

## Need help?

- If you have an open PR, tag the PR reviewers in comment with your question: `@carlyrevier, @jehchow`
- Open an issue in this repo and tag the PR reviewers.

### CODE REVIEW

**Comment by anxumalo** [comment]
Hi @carlyrevier, @jehchow, I'm struggling with the steps in this exercise and have a few  a few observations & questions. The key issue is that the **Compare changes** view in step 5 looks different.

When I reached step 5 and reviewed **Compare changes**, I do not see the same options as shown in the screenshot. For example, there are only two drop-drown options for: 

`base: main` <— `compare: anxumalo-patch-1`

However, your screenshot shows four drop-down options:

`base repository: MicrosoftDocs/Contribute` .. `base: main` <— `head repository: new-learn-contributor/Contribute` .. `compare: patch-2`

1. Why can't I see the additional drop-downs in my PR? Did I miss some steps?
2. Do I need to merge my PR into my branch (`anxumalo-patch-1`) before raising a PR against the MicrosoftDocs repo? I’m new to working with forks! 
3. Why do I see a different path for the changed file? 
    - my PR changes: `Contribute/content/index.html`
    - your PR changes: `Contribute/Contribute/index.html`

I'd love to hear your advice. Thanks in advance!

**Comment by carlyrevier** [comment]
Hi @anxumalo - Thank you so much for bringing this to our attention, and thanks for being a contributor!

1. When you're in the "Comparing changes" view, do you see a link that says "compare across forks" like in the image below?

image

If you select that, you should then see four dropdowns instead of two. Let me know if this works for you!

2. I don't believe so. I think comparing across forks (like I described above) should work.

3. We recently moved some files around in the GitHub folder, so the screenshot is simply out of date. What you're seeing is correct: the files are now stored in /Contribute/content, rather than /Contribute/Contribute. I'll pass along this feedback to the person who wrote the module so she can update her screenshots and info.

**Comment by carlyrevier** [comment]
@anxumalo - Also, you may have to redo the exercise and reopen a new PR. This PR is currently open in your fork; I don't think you can change forks once you've opened a PR.

**Comment by anxumalo** [comment]
> Hi @anxumalo - Thank you so much for bringing this to our attention, and thanks for being a contributor!
> 
> 1. When you're in the "Comparing changes" view, do you see a link that says "compare across forks" like in the image below?
> ...
>     If you select that, you should then see four dropdowns instead of two. Let me know if this works for you!
> 
> 2. I don't believe so. I think comparing across forks (like I described above) should work.
> 3. We recently moved some files around in the GitHub folder, so the screenshot is simply out of date. What you're seeing is correct: the files are now stored in /Contribute/content, rather than /Contribute/Contribute. I'll pass along this feedback to the person who wrote the module so she can update her screenshots and info.

Hi @carlyrevier - Thanks for the pointers, I've now seen how to compare across forks using my 2nd patch branch. The four drop-downs are clearly visible. It's amazing how different the screens look when working from a fork. ;-)

I'll close this PR and continue in a new one. Thanks again for your help - much appreciated!

**Comment by carlyrevier** [comment]
> > Hi @anxumalo - Thank you so much for bringing this to our attention, and thanks for being a contributor!
> > 
> > 1. When you're in the "Comparing changes" view, do you see a link that says "compare across forks" like in the image below?
> >    ...
> >    If you select that, you should then see four dropdowns instead of two. Let me know if this works for you!
> > 2. I don't believe so. I think comparing across forks (like I described above) should work.
> > 3. We recently moved some files around in the GitHub folder, so the screenshot is simply out of date. What you're seeing is correct: the files are now stored in /Contribute/content, rather than /Contribute/Contribute. I'll pass along this feedback to the person who wrote the module so she can update her screenshots and info.
> 
> Hi @carlyrevier - Thanks for the pointers, I've now seen how to compare across forks using my 2nd patch branch. The four drop-downs are clearly visible. It's amazing how different the screens look when working from a fork. ;-)
> 
> I'll close this PR and continue in a new one. Thanks again for your help - much appreciated!

Thanks for the feedback! We'll work on updating the screenshots in the training module so they show the accurate experience. I think this is a recent GitHub change!

**Pull request closed without merging**
